config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resource :profile
  end

  root to: 'pages#home'
  get '/about' => 'pages#about'

  resources :contacts
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, :email, presence: true
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :users
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :plan
  has_one :profile

  # create customer using hidden field on the view page
  attr_accessor :stripe_card_token
  # save user after is be created by stripe
  def save_with_payment
    if valid?
      customer = Stripe::Customer.create(description: email, plan: plan_id, source: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :stripe_card_token, :email, :password, :password_confirmation) }
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      name  = params[:contact][:name]
      email = params[:contact][:email]
      body  = params[:contact][:comments]

      ContactMailer.welcome_email(name, email, body).deliver_now

      flash[:success] = "Message sent."
      redirect_to root_path
      else
      flash[:danger] = "Error occurred, please try again..."
      redirect_to new_contact_path
    end
  end

  private
    def contact_params
      params.require(:contact).permit(:name, :email, :comments)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @basic = Plan.find(1)
    @pro   = Plan.find(2)
  end

  def about

  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :only_current_user

  def new
    @user    = User.find(params[:user_id])
    @profile = Profile.new
  end

  def create
    @user    = User.find(params[:user_id])
    @profile = @user.build_profile(profile_params)

    if @profile.save
      flash[:success] = "Your profile is been created."
      redirect_to user_path(params[:user_id])
    else
      flash[:ganger] = "You are missing some info, please try again..."
      render action: :new
    end
  end

  def edit
    @user    = User.find(params[:user_id])
    @profile = @user.profile
  end

  def update
    @user    = User.find(params[:user_id])
    @profile = @user.profile
    if @profile.update_attributes(profile_params)
      flash[:success] = "Your profile is been updated."
      redirect_to user_path(params[:user_id])
    else
      flash[:notice] = "Your profile needs attention."
      render 'edit'
    end
  end

  private
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :job_title, :description, :phone_number, :contact_email, :location, :avatar )
    end

    def only_current_user
      @user = User.find(params[:user_id])
      redirect_to root_url unless @user == current_user
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def create
    super do |resource|
      if params[:plan]
        resource.plan_id = params[:plan]
        if resource.plan_id == 2
          resource.save_with_payment
        else
          resource.save
        end
      end
    end
  end

 private
  def select_plan
    unless params[:plan] && (params[:plan] == '1' || params[:plan] == '2')
      flash[:notice] = "Please select a membership plan to sign up."
      redirect_to root_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def job_title_icon
    if @user.profile.job_title == "Developer"
      "<i class='fa fa-code'></i>".html_safe
    elsif @user.profile.job_title == "Designer"
      "<i class='fa fa-paint-brush'></i>".html_safe
    elsif @user.profile.job_title == "Entrepreneur"
      "<i class='fa fa-lightbulb-o'></i>".html_safe
    else @user.profile.job_title == "Investor"
      "<i class='fa fa-dollar'></i>".html_safe
    end
  end
end

app/views/contacts/create.html.erb
<p>Form is created...</p>

app/views/contacts/new.html.erb
<div class="row">
  <%= form_for(@contact, html: {class: 'form-horizontal'}) do |f| %>
    <% if @contact.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

        <ul>
        <% @contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field form-group">
      <%= f.label :name, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>

    <div class="field form-group">
      <%= f.label :email, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.email_field :email, class: 'form-control' %>
      </div>
    </div>

    <div class="field form-group">
      <%= f.label :comments, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.text_area :comments, class: 'form-control' %>
      </div>
    </div>

    <div class="actions form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "Submit", class: "btn btn-default" %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Code Saas</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'https://js.stripe.com/v2/', type: "text/javascript" %>
  <%= javascript_include_tag 'application' %>
  <%= tag :meta, name: "stripe-key", content: STRIPE_PUBLIC_KEY  %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <%= link_to root_path, class: "navbar-brand" do %>
            <i class="fa fa-code"></i>
            Code SaaS
          <% end %>
        </div>



        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", new_contact_path %></li>
          </ul>

          <ul class="nav navbar-nav navbar-right hmenu">
            <%= render 'devise/menu/registration_items' %>
          </ul>

        </div><!--/.nav-collapse -->




      </div>
    </nav
    >

  <div id="main-container" class="container">
    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "alert alert-#{key}" %>
    <% end %>
    <div class="row">
      <div class="col-xs-12">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h2>Home of Code SaaS</h2>
  <h3>A membership where developer meets clients</h3>
</div>


<div class="row">
  <% if user_signed_in? %>
    <div class="col-md-6">
      <div class="well">
        <% if current_user.profile %>
          <p> <%= link_to "Edit Profile", edit_user_profile_path(current_user)  %></p>
          <p><%= link_to "View Profile", current_user %></p>
          <p><%= link_to "Community Members", users_path %></p>
        <% else %>
          <%= link_to "New Profile", new_user_profile_path(current_user) if current_user %>
        <% end %>
      </div>
    </div>
  <% else %>
    <div class="col-md-6">
      <div class="well">
        <h2 class="text-center">Basic Membership</h2>
        <h4>Join the community and enjoy getting together with your peers.</h4>
        <p> <%= link_to "Join for Free", new_user_registration_path(plan: @basic.id), class:"btn btn-primary btn-large btn-block" %>
        </p>
      </div>
    </div>
    <div class="col-md-6">
      <div class="well">
        <h2 class="text-center">Pro Membership</h2>
        <h4>Enjoy full access to all community members for $10 a month.</h4>
        <br>
        <p> <%= link_to "Get Full Access", new_user_registration_path(plan: @pro.id), class:"btn btn-success btn-large btn-block" %>
        </p>
      </div>
    </div>
  <% end %>
</div>

app/views/profiles/_form.html.erb
        <%= form_for @profile, url: user_profile_path, html: { multipart: true }  do |f| %>
          <div class="form-group">
            <%= f.label :first_name %>
            <%= f.text_field :first_name, class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :last_name %>
            <%= f.text_field :last_name, class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :job_title %>
            <%= f.select :job_title, ['Developer', 'Designer', 'Entrepreneur', 'Investor'], {}, class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :phone_number %>
            <%= f.text_field :phone_number, class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :contact_email %>
            <%= f.email_field :contact_email, class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :avatar %>
            <%= f.file_field :avatar, class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :location %>
            <%= f.text_field :location, class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class:"form-control", rows: '10' %>
          </div>
          <div class="actions form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <%= f.submit class: "btn btn-primary" %>
            </div>
          </div>

        <% end %>

app/views/profiles/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offest-3">
    <h1 class="text-center">Edit your profile</h1>
    <p class="text-center">Be a part of the developer and business mind community</p>
      <div class="well">

        <%= render 'form' %>

      </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offest-3">
    <h1 class="text-center">Create your profile</h1>
    <p class="text-center">Be a part of the developer and business mind community</p>
      <div class="well">
        <%= form_for @profile, url: user_profile_path do |f| %>
          <div class="form-group">
            <%= f.label :first_name %>
            <%= f.text_field :first_name, class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :first_name %>
            <%= f.text_field :first_name, class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :last_name %>
            <%= f.text_field :last_name, class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :job_title %>
            <%= f.select :job_title, ['Developer', 'Designer', 'Entrepreneur', 'Investor'], {}, class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :phone_number %>
            <%= f.text_field :phone_number, class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :location %>
            <%= f.text_field :location, class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class:"form-control", rows: '10' %>
          </div>
          <div class="actions form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <%= f.submit "Create Profile", class: "btn btn-primary" %>
            </div>
          </div>

        <% end %>
      </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-2">
    <ul class="list-unstyled">
      <% @users.each do |user| %>
        <% if user.profile %>
          <li>
            <div class="well row <%= cycle('white-bg', '') %>">
              <div class="col-xs-3 text-center">
                <%= link_to user do %>
                  <%= image_tag user.profile.avatar.url(:thumb), alt: "#{user.profile.job_title}", title: "#{user.profile.job_title}" %>
                <% end %>
              </div>
              <div>
              <h3>
                <%= link_to user do %>
                  <%= user.profile.first_name %> <%= user.profile.last_name %>
                <% end %>
              </h3>
              <p>
                <%= user.profile.job_title %>
                <% if user.plan_id == 2 %>
                  <span class="label label-success">PRO</span>
                <% end %>
              </p>
              </div>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>

  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-3 text-center">
    <%= image_tag @user.profile.avatar.url(:thumb), alt: "#{@user.profile.job_title}", title: "#{@user.profile.job_title}" %>
  </div>

  <div class="col-xs-9">
    <h1><%= @user.profile.first_name %> <%= @user.profile.last_name %></h1>
    <h3>
      <span class="job_title_icon"><%= job_title_icon %></span>
      <%= @user.profile.job_title %>
    </h3>

    <p>
      <i class="fa fa-globe"></i>
      <%= @user.profile.location.capitalize %>
    </p>


    <% if current_user.plan_id == 1 %>
        <p class="alert alert-success">
        In order to see all details you need to subscribe to
        <%= link_to "Pro plan", new_user_registration_path  %>
        </p>
    <% end %>

    <% if current_user.plan_id == 2 %>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-info"></i> Contact</h3>
      </div>
      <div class="panel-body">
        <p>
          <i class="fa fa-phone"></i>
          <%= @user.profile.phone_number %>
        </p>
        <p>
          <i class="fa fa-envelope-o"></i>
          <%= @user.profile.contact_email %>
        </p>
      </div>
    </div>



   <% end %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-file-text-o"></i> Description</h3>
      </div>
      <div class="panel-body">
        <p>
          <%= simple_format(@user.profile.description) %>
        </p>
      </div>
    </div>

  </div>
</div>